# Approve a deployment if time matches one of these
allow:
  - "* 8-15 * * 1-5" # week days 8-15

# Reject a deployment if time matches any of the these
deny:
  - "* 12-13 * * *" # during lunch

# Approve if commit message matches
override: "force-deploy"
