# Approve a deployment if time matches one of these
allow:
  - "* 7-14 * * 1-5" # week days

# Reject a deployment if time matches any of the these
deny:
  - "* 11-12 * * *" # during lunch

# Approve if commit message matches
override: "force-deploy"
