name: TEST
on:
  push:

permissions:
  contents: write
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest
    depends-on:
      - auto-deploy

    environment:
      name: Test

    steps:
      - run: echo "hello world"


  auto-deploy:
    runs-on: ubuntu-latest

    steps:
      - run: echo "hello world"
