name: TEST
on:
  push:

permissions:
  contents: write
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest
    needs:
      - auto-deploy

    environment:
      name: Test

    steps:
      - run: echo "hello world"


  auto-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            console.log(context);
